/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContributionId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Topic = IDL.Variant({
  'businessPlanning' : IDL.Null,
  'socialAds' : IDL.Null,
  'branding' : IDL.Null,
  'googleMaps' : IDL.Null,
  'techUpgrades' : IDL.Null,
});
export const GuideId = IDL.Nat;
export const GuideInput = IDL.Record({
  'title' : IDL.Text,
  'topic' : Topic,
  'content' : IDL.Text,
  'businessTypeTags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'recommendedNext' : IDL.Vec(GuideId),
  'excerpt' : IDL.Text,
  'readTimeMinutes' : IDL.Nat,
});
export const AuthorType = IDL.Variant({
  'admin' : IDL.Null,
  'community' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Guide = IDL.Record({
  'id' : GuideId,
  'title' : IDL.Text,
  'topic' : Topic,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'businessTypeTags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'authorType' : AuthorType,
  'publishedAt' : IDL.Opt(Timestamp),
  'recommendedNext' : IDL.Vec(GuideId),
  'excerpt' : IDL.Text,
  'readTimeMinutes' : IDL.Nat,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ProviderHealthStatus = IDL.Record({
  'provider' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
  'isHealthy' : IDL.Opt(IDL.Bool),
  'statusUrl' : IDL.Text,
  'lastCheckedAt' : IDL.Opt(IDL.Text),
});
export const AdminStats = IDL.Record({
  'totalPublished' : IDL.Nat,
  'recentGuides' : IDL.Vec(Guide),
  'pendingContributions' : IDL.Nat,
});
export const TeamSize = IDL.Variant({
  'solo' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const SubscriptionTier = IDL.Variant({
  'free' : IDL.Null,
  'paid' : IDL.Null,
});
export const Goal = IDL.Variant({
  'businessPlanning' : IDL.Null,
  'socialAds' : IDL.Null,
  'googleMaps' : IDL.Null,
});
export const IndustryType = IDL.Variant({
  'retail' : IDL.Null,
  'other' : IDL.Null,
  'deli' : IDL.Null,
  'consulting' : IDL.Null,
  'salon' : IDL.Null,
  'onlineServices' : IDL.Null,
  'newBusiness' : IDL.Null,
  'poolHall' : IDL.Null,
  'restaurant' : IDL.Null,
});
export const BusinessProfile = IDL.Record({
  'teamSize' : TeamSize,
  'signupDate' : IDL.Opt(IDL.Int),
  'name' : IDL.Opt(IDL.Text),
  'subscriptionTier' : IDL.Opt(SubscriptionTier),
  'businessName' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'goals' : IDL.Vec(Goal),
  'industryType' : IndustryType,
  'location' : IDL.Text,
});
export const CourseId = IDL.Nat;
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'expiresAt' : Timestamp,
  'endDate' : IDL.Text,
  'isExpired' : IDL.Bool,
  'fetchedAt' : Timestamp,
  'borough' : IDL.Text,
  'description' : IDL.Text,
  'language' : IDL.Text,
  'addedAt' : Timestamp,
  'category' : IDL.Text,
  'isNew' : IDL.Bool,
  'registrationUrl' : IDL.Text,
  'courseType' : IDL.Text,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
  'startDate' : IDL.Text,
});
export const ContributionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Contribution = IDL.Record({
  'id' : ContributionId,
  'status' : ContributionStatus,
  'title' : IDL.Text,
  'topic' : Topic,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'submittedAt' : Timestamp,
  'reviewedAt' : IDL.Opt(Timestamp),
  'businessContext' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
});
export const ProviderStats = IDL.Record({
  'provider' : IDL.Text,
  'totalOutages' : IDL.Nat,
  'averageDurationHours' : IDL.Float64,
  'mostCommonIncidentType' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const GuideFilter = IDL.Record({
  'topic' : IDL.Opt(Topic),
  'keyword' : IDL.Opt(IDL.Text),
  'businessTypeTag' : IDL.Opt(IDL.Text),
});
export const OutageFilter = IDL.Record({
  'provider' : IDL.Opt(IDL.Text),
  'endDate' : IDL.Opt(IDL.Text),
  'incidentType' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Opt(IDL.Text),
});
export const OutageId = IDL.Nat;
export const OutageRecord = IDL.Record({
  'id' : OutageId,
  'provider' : IDL.Text,
  'date' : IDL.Text,
  'durationHours' : IDL.Float64,
  'nycImpactDescription' : IDL.Text,
  'regionScope' : IDL.Text,
  'incidentType' : IDL.Text,
});
export const ContributionInput = IDL.Record({
  'title' : IDL.Text,
  'topic' : Topic,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'businessContext' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approveContribution' : IDL.Func([ContributionId], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGuide' : IDL.Func([GuideInput], [Guide], []),
  'deleteGuide' : IDL.Func([GuideId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'fetchCourses' : IDL.Func([], [], []),
  'fetchProviderHealthStatus' : IDL.Func(
      [],
      [IDL.Vec(ProviderHealthStatus)],
      [],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getExpiredCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getFeaturedGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
  'getGuide' : IDL.Func([GuideId], [IDL.Opt(Guide)], ['query']),
  'getLastUpdated' : IDL.Func([], [Timestamp], ['query']),
  'getMyContributions' : IDL.Func([], [IDL.Vec(Contribution)], ['query']),
  'getPersonalizedRecommendations' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
  'getProviderHealthStatus' : IDL.Func(
      [],
      [IDL.Vec(ProviderHealthStatus)],
      ['query'],
    ),
  'getProviderStats' : IDL.Func([], [IDL.Vec(ProviderStats)], ['query']),
  'getUpcomingCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listGuides' : IDL.Func([GuideFilter], [IDL.Vec(Guide)], ['query']),
  'listOutages' : IDL.Func([OutageFilter], [IDL.Vec(OutageRecord)], ['query']),
  'listPendingContributions' : IDL.Func([], [IDL.Vec(Contribution)], ['query']),
  'rejectContribution' : IDL.Func(
      [ContributionId, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setGuidePublished' : IDL.Func([GuideId, IDL.Bool], [IDL.Bool], []),
  'submitContribution' : IDL.Func([ContributionInput], [Contribution], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateGuide' : IDL.Func([GuideId, GuideInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContributionId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Topic = IDL.Variant({
    'businessPlanning' : IDL.Null,
    'socialAds' : IDL.Null,
    'branding' : IDL.Null,
    'googleMaps' : IDL.Null,
    'techUpgrades' : IDL.Null,
  });
  const GuideId = IDL.Nat;
  const GuideInput = IDL.Record({
    'title' : IDL.Text,
    'topic' : Topic,
    'content' : IDL.Text,
    'businessTypeTags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'recommendedNext' : IDL.Vec(GuideId),
    'excerpt' : IDL.Text,
    'readTimeMinutes' : IDL.Nat,
  });
  const AuthorType = IDL.Variant({
    'admin' : IDL.Null,
    'community' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Guide = IDL.Record({
    'id' : GuideId,
    'title' : IDL.Text,
    'topic' : Topic,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'businessTypeTags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'authorType' : AuthorType,
    'publishedAt' : IDL.Opt(Timestamp),
    'recommendedNext' : IDL.Vec(GuideId),
    'excerpt' : IDL.Text,
    'readTimeMinutes' : IDL.Nat,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ProviderHealthStatus = IDL.Record({
    'provider' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
    'isHealthy' : IDL.Opt(IDL.Bool),
    'statusUrl' : IDL.Text,
    'lastCheckedAt' : IDL.Opt(IDL.Text),
  });
  const AdminStats = IDL.Record({
    'totalPublished' : IDL.Nat,
    'recentGuides' : IDL.Vec(Guide),
    'pendingContributions' : IDL.Nat,
  });
  const TeamSize = IDL.Variant({
    'solo' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const SubscriptionTier = IDL.Variant({
    'free' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'businessPlanning' : IDL.Null,
    'socialAds' : IDL.Null,
    'googleMaps' : IDL.Null,
  });
  const IndustryType = IDL.Variant({
    'retail' : IDL.Null,
    'other' : IDL.Null,
    'deli' : IDL.Null,
    'consulting' : IDL.Null,
    'salon' : IDL.Null,
    'onlineServices' : IDL.Null,
    'newBusiness' : IDL.Null,
    'poolHall' : IDL.Null,
    'restaurant' : IDL.Null,
  });
  const BusinessProfile = IDL.Record({
    'teamSize' : TeamSize,
    'signupDate' : IDL.Opt(IDL.Int),
    'name' : IDL.Opt(IDL.Text),
    'subscriptionTier' : IDL.Opt(SubscriptionTier),
    'businessName' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'goals' : IDL.Vec(Goal),
    'industryType' : IndustryType,
    'location' : IDL.Text,
  });
  const CourseId = IDL.Nat;
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'expiresAt' : Timestamp,
    'endDate' : IDL.Text,
    'isExpired' : IDL.Bool,
    'fetchedAt' : Timestamp,
    'borough' : IDL.Text,
    'description' : IDL.Text,
    'language' : IDL.Text,
    'addedAt' : Timestamp,
    'category' : IDL.Text,
    'isNew' : IDL.Bool,
    'registrationUrl' : IDL.Text,
    'courseType' : IDL.Text,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const ContributionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Contribution = IDL.Record({
    'id' : ContributionId,
    'status' : ContributionStatus,
    'title' : IDL.Text,
    'topic' : Topic,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'submittedAt' : Timestamp,
    'reviewedAt' : IDL.Opt(Timestamp),
    'businessContext' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
  });
  const ProviderStats = IDL.Record({
    'provider' : IDL.Text,
    'totalOutages' : IDL.Nat,
    'averageDurationHours' : IDL.Float64,
    'mostCommonIncidentType' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const GuideFilter = IDL.Record({
    'topic' : IDL.Opt(Topic),
    'keyword' : IDL.Opt(IDL.Text),
    'businessTypeTag' : IDL.Opt(IDL.Text),
  });
  const OutageFilter = IDL.Record({
    'provider' : IDL.Opt(IDL.Text),
    'endDate' : IDL.Opt(IDL.Text),
    'incidentType' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Opt(IDL.Text),
  });
  const OutageId = IDL.Nat;
  const OutageRecord = IDL.Record({
    'id' : OutageId,
    'provider' : IDL.Text,
    'date' : IDL.Text,
    'durationHours' : IDL.Float64,
    'nycImpactDescription' : IDL.Text,
    'regionScope' : IDL.Text,
    'incidentType' : IDL.Text,
  });
  const ContributionInput = IDL.Record({
    'title' : IDL.Text,
    'topic' : Topic,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'businessContext' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approveContribution' : IDL.Func([ContributionId], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGuide' : IDL.Func([GuideInput], [Guide], []),
    'deleteGuide' : IDL.Func([GuideId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'fetchCourses' : IDL.Func([], [], []),
    'fetchProviderHealthStatus' : IDL.Func(
        [],
        [IDL.Vec(ProviderHealthStatus)],
        [],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getExpiredCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getFeaturedGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
    'getGuide' : IDL.Func([GuideId], [IDL.Opt(Guide)], ['query']),
    'getLastUpdated' : IDL.Func([], [Timestamp], ['query']),
    'getMyContributions' : IDL.Func([], [IDL.Vec(Contribution)], ['query']),
    'getPersonalizedRecommendations' : IDL.Func(
        [],
        [IDL.Vec(Guide)],
        ['query'],
      ),
    'getProviderHealthStatus' : IDL.Func(
        [],
        [IDL.Vec(ProviderHealthStatus)],
        ['query'],
      ),
    'getProviderStats' : IDL.Func([], [IDL.Vec(ProviderStats)], ['query']),
    'getUpcomingCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listGuides' : IDL.Func([GuideFilter], [IDL.Vec(Guide)], ['query']),
    'listOutages' : IDL.Func(
        [OutageFilter],
        [IDL.Vec(OutageRecord)],
        ['query'],
      ),
    'listPendingContributions' : IDL.Func(
        [],
        [IDL.Vec(Contribution)],
        ['query'],
      ),
    'rejectContribution' : IDL.Func(
        [ContributionId, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setGuidePublished' : IDL.Func([GuideId, IDL.Bool], [IDL.Bool], []),
    'submitContribution' : IDL.Func([ContributionInput], [Contribution], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateGuide' : IDL.Func([GuideId, GuideInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };