/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalPublished' : bigint,
  'recentGuides' : Array<Guide>,
  'pendingContributions' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type AuthorType = { 'admin' : null } |
  { 'community' : null };
export interface BusinessProfile {
  'teamSize' : TeamSize,
  'signupDate' : [] | [bigint],
  'name' : [] | [string],
  'subscriptionTier' : [] | [SubscriptionTier],
  'businessName' : string,
  'email' : [] | [string],
  'goals' : Array<Goal>,
  'industryType' : IndustryType,
  'location' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Contribution {
  'id' : ContributionId,
  'status' : ContributionStatus,
  'title' : string,
  'topic' : Topic,
  'content' : string,
  'authorName' : string,
  'rejectionReason' : [] | [string],
  'submittedAt' : Timestamp,
  'reviewedAt' : [] | [Timestamp],
  'businessContext' : string,
  'authorPrincipal' : Principal,
}
export type ContributionId = bigint;
export interface ContributionInput {
  'title' : string,
  'topic' : Topic,
  'content' : string,
  'authorName' : string,
  'businessContext' : string,
}
export type ContributionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Course {
  'id' : CourseId,
  'title' : string,
  'expiresAt' : Timestamp,
  'endDate' : string,
  'isExpired' : boolean,
  'fetchedAt' : Timestamp,
  'borough' : string,
  'description' : string,
  'language' : string,
  'addedAt' : Timestamp,
  'category' : string,
  'isNew' : boolean,
  'registrationUrl' : string,
  'courseType' : string,
  'location' : string,
  'contactPhone' : string,
  'startDate' : string,
}
export type CourseId = bigint;
export type Goal = { 'businessPlanning' : null } |
  { 'socialAds' : null } |
  { 'googleMaps' : null };
export interface Guide {
  'id' : GuideId,
  'title' : string,
  'topic' : Topic,
  'content' : string,
  'isPublished' : boolean,
  'businessTypeTags' : Array<string>,
  'authorName' : string,
  'authorType' : AuthorType,
  'publishedAt' : [] | [Timestamp],
  'recommendedNext' : Array<GuideId>,
  'excerpt' : string,
  'readTimeMinutes' : bigint,
}
export interface GuideFilter {
  'topic' : [] | [Topic],
  'keyword' : [] | [string],
  'businessTypeTag' : [] | [string],
}
export type GuideId = bigint;
export interface GuideInput {
  'title' : string,
  'topic' : Topic,
  'content' : string,
  'businessTypeTags' : Array<string>,
  'authorName' : string,
  'recommendedNext' : Array<GuideId>,
  'excerpt' : string,
  'readTimeMinutes' : bigint,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type IndustryType = { 'retail' : null } |
  { 'other' : null } |
  { 'deli' : null } |
  { 'consulting' : null } |
  { 'salon' : null } |
  { 'onlineServices' : null } |
  { 'newBusiness' : null } |
  { 'poolHall' : null } |
  { 'restaurant' : null };
export interface OutageFilter {
  'provider' : [] | [string],
  'endDate' : [] | [string],
  'incidentType' : [] | [string],
  'startDate' : [] | [string],
}
export type OutageId = bigint;
export interface OutageRecord {
  'id' : OutageId,
  'provider' : string,
  'date' : string,
  'durationHours' : number,
  'nycImpactDescription' : string,
  'regionScope' : string,
  'incidentType' : string,
}
export interface ProviderHealthStatus {
  'provider' : string,
  'errorMessage' : [] | [string],
  'isHealthy' : [] | [boolean],
  'statusUrl' : string,
  'lastCheckedAt' : [] | [string],
}
export interface ProviderStats {
  'provider' : string,
  'totalOutages' : bigint,
  'averageDurationHours' : number,
  'mostCommonIncidentType' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type SubscriptionTier = { 'free' : null } |
  { 'paid' : null };
export type TeamSize = { 'solo' : null } |
  { 'small' : null } |
  { 'medium' : null };
export type Timestamp = bigint;
export type Topic = { 'businessPlanning' : null } |
  { 'socialAds' : null } |
  { 'branding' : null } |
  { 'googleMaps' : null } |
  { 'techUpgrades' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveContribution' : ActorMethod<[ContributionId], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGuide' : ActorMethod<[GuideInput], Guide>,
  'deleteGuide' : ActorMethod<[GuideId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'fetchCourses' : ActorMethod<[], undefined>,
  'fetchProviderHealthStatus' : ActorMethod<[], Array<ProviderHealthStatus>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getExpiredCourses' : ActorMethod<[], Array<Course>>,
  'getFeaturedGuides' : ActorMethod<[], Array<Guide>>,
  'getGuide' : ActorMethod<[GuideId], [] | [Guide]>,
  'getLastUpdated' : ActorMethod<[], Timestamp>,
  'getMyContributions' : ActorMethod<[], Array<Contribution>>,
  'getPersonalizedRecommendations' : ActorMethod<[], Array<Guide>>,
  'getProviderHealthStatus' : ActorMethod<[], Array<ProviderHealthStatus>>,
  'getProviderStats' : ActorMethod<[], Array<ProviderStats>>,
  'getUpcomingCourses' : ActorMethod<[], Array<Course>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listGuides' : ActorMethod<[GuideFilter], Array<Guide>>,
  'listOutages' : ActorMethod<[OutageFilter], Array<OutageRecord>>,
  'listPendingContributions' : ActorMethod<[], Array<Contribution>>,
  'rejectContribution' : ActorMethod<[ContributionId, [] | [string]], boolean>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'schema' : ActorMethod<[], string>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setGuidePublished' : ActorMethod<[GuideId, boolean], boolean>,
  'submitContribution' : ActorMethod<[ContributionInput], Contribution>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateGuide' : ActorMethod<[GuideId, GuideInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];