/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface OutageRecord {
    id: OutageId;
    provider: string;
    date: string;
    durationHours: number;
    nycImpactDescription: string;
    regionScope: string;
    incidentType: string;
}
export interface _UnsubscribeSuccess {
    topic_name?: string;
}
export interface ProviderHealthStatus {
    provider: string;
    errorMessage?: string;
    isHealthy?: boolean;
    statusUrl: string;
    lastCheckedAt?: string;
}
export interface Course {
    id: CourseId;
    title: string;
    expiresAt: Timestamp;
    endDate: string;
    isExpired: boolean;
    fetchedAt: Timestamp;
    borough: string;
    description: string;
    language: string;
    addedAt: Timestamp;
    category: string;
    isNew: boolean;
    registrationUrl: string;
    courseType: string;
    location: string;
    contactPhone: string;
    startDate: string;
}
export interface GuideFilter {
    topic?: Topic;
    keyword?: string;
    businessTypeTag?: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface Cell {
    value: Value;
    name: string;
}
export type CourseId = bigint;
export interface Contribution {
    id: ContributionId;
    status: ContributionStatus;
    title: string;
    topic: Topic;
    content: string;
    authorName: string;
    rejectionReason?: string;
    submittedAt: Timestamp;
    reviewedAt?: Timestamp;
    businessContext: string;
    authorPrincipal: Principal;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface _UnsubscribeError {
}
export type ContributionId = bigint;
export interface ContributionInput {
    title: string;
    topic: Topic;
    content: string;
    authorName: string;
    businessContext: string;
}
export interface ProviderStats {
    provider: string;
    totalOutages: bigint;
    averageDurationHours: number;
    mostCommonIncidentType: string;
}
export interface NewsletterContent {
    htmlBody: string;
    subject: string;
}
export interface Guide {
    id: GuideId;
    title: string;
    topic: Topic;
    content: string;
    isPublished: boolean;
    businessTypeTags: Array<string>;
    authorName: string;
    authorType: AuthorType;
    publishedAt?: Timestamp;
    recommendedNext: Array<GuideId>;
    excerpt: string;
    readTimeMinutes: bigint;
}
export type _CaffeineEmailUnsubscribeResult = {
    __kind__: "Ok";
    Ok: _UnsubscribeSuccess;
} | {
    __kind__: "Err";
    Err: _UnsubscribeError;
};
export interface HttpHeader {
    value: string;
    name: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface GuideInput {
    title: string;
    topic: Topic;
    content: string;
    businessTypeTags: Array<string>;
    authorName: string;
    recommendedNext: Array<GuideId>;
    excerpt: string;
    readTimeMinutes: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface OutageFilter {
    provider?: string;
    endDate?: string;
    incidentType?: string;
    startDate?: string;
}
export interface _CaffeineEmailUnsubscribeArgs {
    recipient_email: string;
    topic_id: number;
}
export interface Topic__1 {
    id: bigint;
    name: string;
}
export type OutageId = bigint;
export interface AdminStats {
    totalPublished: bigint;
    recentGuides: Array<Guide>;
    pendingContributions: bigint;
}
export type GuideId = bigint;
export interface BusinessProfile {
    teamSize: TeamSize;
    signupDate?: bigint;
    name?: string;
    subscriptionTier?: SubscriptionTier;
    businessName: string;
    email?: string;
    goals: Array<Goal>;
    industryType: IndustryType;
    location: string;
}
export enum AuthorType {
    admin = "admin",
    community = "community"
}
export enum ContributionStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Frequency {
    both = "both",
    monthly = "monthly",
    weekly = "weekly"
}
export enum Goal {
    businessPlanning = "businessPlanning",
    socialAds = "socialAds",
    googleMaps = "googleMaps"
}
export enum IndustryType {
    retail = "retail",
    other = "other",
    deli = "deli",
    consulting = "consulting",
    salon = "salon",
    onlineServices = "onlineServices",
    newBusiness = "newBusiness",
    poolHall = "poolHall",
    restaurant = "restaurant"
}
export enum SubscriptionTier {
    free = "free",
    paid = "paid"
}
export enum TeamSize {
    solo = "solo",
    small = "small",
    medium = "medium"
}
export enum Topic {
    businessPlanning = "businessPlanning",
    socialAds = "socialAds",
    branding = "branding",
    googleMaps = "googleMaps",
    techUpgrades = "techUpgrades"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineEmailUnsubscribeFromTopic(args: _CaffeineEmailUnsubscribeArgs): Promise<_CaffeineEmailUnsubscribeResult>;
    _caffeineEmailVerify(email: string): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addNewsletterTopic(name: string): Promise<bigint>;
    approveContribution(id: ContributionId): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGuide(input: GuideInput): Promise<Guide>;
    deleteGuide(id: GuideId): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    fetchCourses(): Promise<void>;
    fetchProviderHealthStatus(): Promise<Array<ProviderHealthStatus>>;
    getAdminStats(): Promise<AdminStats>;
    getBusinessProfile(): Promise<BusinessProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCourses(): Promise<Array<Course>>;
    getExpiredCourses(): Promise<Array<Course>>;
    getFeaturedGuides(): Promise<Array<Guide>>;
    getGuide(id: GuideId): Promise<Guide | null>;
    getLastUpdated(): Promise<Timestamp>;
    getMyContributions(): Promise<Array<Contribution>>;
    getNewsletterContent(topicId: bigint): Promise<NewsletterContent | null>;
    getPersonalizedRecommendations(): Promise<Array<Guide>>;
    getProviderHealthStatus(): Promise<Array<ProviderHealthStatus>>;
    getProviderStats(): Promise<Array<ProviderStats>>;
    getUpcomingCourses(): Promise<Array<Course>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listGuides(filter: GuideFilter): Promise<Array<Guide>>;
    listNewsletterSubscribers(topicId: bigint): Promise<Array<[string, boolean]>>;
    listNewsletterTopics(): Promise<Array<Topic__1>>;
    listOutages(filter: OutageFilter): Promise<Array<OutageRecord>>;
    listPendingContributions(): Promise<Array<Contribution>>;
    rejectContribution(id: ContributionId, reason: string | null): Promise<boolean>;
    removeNewsletterTopic(topicId: bigint): Promise<void>;
    renameNewsletterTopic(topicId: bigint, newName: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveBusinessProfile(profile: BusinessProfile): Promise<void>;
    schema(): Promise<string>;
    sendMonthlyNewsletter(): Promise<void>;
    sendWeeklyNewsletter(): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setGuidePublished(id: GuideId, published: boolean): Promise<boolean>;
    setNewsletterContent(topicId: bigint, subject: string, htmlBody: string): Promise<void>;
    submitContribution(input: ContributionInput): Promise<Contribution>;
    subscribeToNewsletter(firstName: string, email: string, frequency: Frequency): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateGuide(id: GuideId, input: GuideInput): Promise<boolean>;
}
import type { AdminStats as _AdminStats, ApprovalStatus as _ApprovalStatus, AuthorType as _AuthorType, BusinessProfile as _BusinessProfile, Cell as _Cell, Contribution as _Contribution, ContributionId as _ContributionId, ContributionInput as _ContributionInput, ContributionStatus as _ContributionStatus, Frequency as _Frequency, Goal as _Goal, Guide as _Guide, GuideFilter as _GuideFilter, GuideId as _GuideId, GuideInput as _GuideInput, IndustryType as _IndustryType, NewsletterContent as _NewsletterContent, OutageFilter as _OutageFilter, ProviderHealthStatus as _ProviderHealthStatus, Result as _Result, SubscriptionTier as _SubscriptionTier, TeamSize as _TeamSize, Timestamp as _Timestamp, Topic as _Topic, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, Value as _Value, _CaffeineEmailUnsubscribeResult as __CaffeineEmailUnsubscribeResult, _UnsubscribeError as __UnsubscribeError, _UnsubscribeSuccess as __UnsubscribeSuccess } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineEmailUnsubscribeFromTopic(arg0: _CaffeineEmailUnsubscribeArgs): Promise<_CaffeineEmailUnsubscribeResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineEmailUnsubscribeFromTopic(arg0);
                return from_candid__CaffeineEmailUnsubscribeResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineEmailUnsubscribeFromTopic(arg0);
            return from_candid__CaffeineEmailUnsubscribeResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineEmailVerify(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineEmailVerify(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineEmailVerify(arg0);
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addNewsletterTopic(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsletterTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsletterTopic(arg0);
            return result;
        }
    }
    async approveContribution(arg0: ContributionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveContribution(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveContribution(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGuide(arg0: GuideInput): Promise<Guide> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuide(to_candid_GuideInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Guide_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuide(to_candid_GuideInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Guide_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteGuide(arg0: GuideId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGuide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGuide(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchCourses(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCourses();
            return result;
        }
    }
    async fetchProviderHealthStatus(): Promise<Array<ProviderHealthStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchProviderHealthStatus();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchProviderHealthStatus();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return from_candid_AdminStats_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return from_candid_AdminStats_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourses();
            return result;
        }
    }
    async getExpiredCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpiredCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpiredCourses();
            return result;
        }
    }
    async getFeaturedGuides(): Promise<Array<Guide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedGuides();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedGuides();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuide(arg0: GuideId): Promise<Guide | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuide(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuide(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastUpdated(): Promise<Timestamp> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUpdated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUpdated();
            return result;
        }
    }
    async getMyContributions(): Promise<Array<Contribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyContributions();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyContributions();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsletterContent(arg0: bigint): Promise<NewsletterContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsletterContent(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsletterContent(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersonalizedRecommendations(): Promise<Array<Guide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalizedRecommendations();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalizedRecommendations();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderHealthStatus(): Promise<Array<ProviderHealthStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderHealthStatus();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderHealthStatus();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderStats(): Promise<Array<ProviderStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderStats();
            return result;
        }
    }
    async getUpcomingCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingCourses();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGuides(arg0: GuideFilter): Promise<Array<Guide>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGuides(to_candid_GuideFilter_n61(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGuides(to_candid_GuideFilter_n61(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNewsletterSubscribers(arg0: bigint): Promise<Array<[string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNewsletterSubscribers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNewsletterSubscribers(arg0);
            return result;
        }
    }
    async listNewsletterTopics(): Promise<Array<Topic__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNewsletterTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNewsletterTopics();
            return result;
        }
    }
    async listOutages(arg0: OutageFilter): Promise<Array<OutageRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOutages(to_candid_OutageFilter_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOutages(to_candid_OutageFilter_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listPendingContributions(): Promise<Array<Contribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingContributions();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingContributions();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectContribution(arg0: ContributionId, arg1: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectContribution(arg0, to_candid_opt_n65(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectContribution(arg0, to_candid_opt_n65(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async removeNewsletterTopic(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeNewsletterTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeNewsletterTopic(arg0);
            return result;
        }
    }
    async renameNewsletterTopic(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameNewsletterTopic(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameNewsletterTopic(arg0, arg1);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveBusinessProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBusinessProfile(to_candid_BusinessProfile_n66(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBusinessProfile(to_candid_BusinessProfile_n66(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async sendMonthlyNewsletter(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMonthlyNewsletter();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMonthlyNewsletter();
            return result;
        }
    }
    async sendWeeklyNewsletter(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendWeeklyNewsletter();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendWeeklyNewsletter();
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n77(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n77(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setGuidePublished(arg0: GuideId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setGuidePublished(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGuidePublished(arg0, arg1);
            return result;
        }
    }
    async setNewsletterContent(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNewsletterContent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNewsletterContent(arg0, arg1, arg2);
            return result;
        }
    }
    async submitContribution(arg0: ContributionInput): Promise<Contribution> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContribution(to_candid_ContributionInput_n79(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Contribution_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContribution(to_candid_ContributionInput_n79(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Contribution_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async subscribeToNewsletter(arg0: string, arg1: string, arg2: Frequency): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeToNewsletter(arg0, arg1, to_candid_Frequency_n81(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeToNewsletter(arg0, arg1, to_candid_Frequency_n81(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateGuide(arg0: GuideId, arg1: GuideInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuide(arg0, to_candid_GuideInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuide(arg0, to_candid_GuideInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdminStats_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminStats): AdminStats {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_AuthorType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthorType): AuthorType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BusinessProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessProfile): BusinessProfile {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ContributionStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContributionStatus): ContributionStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Contribution_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contribution): Contribution {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Guide_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Guide): Guide {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_IndustryType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IndustryType): IndustryType {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderHealthStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderHealthStatus): ProviderHealthStatus {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_TeamSize_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamSize): TeamSize {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Topic_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Topic): Topic {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineEmailUnsubscribeResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineEmailUnsubscribeResult): _CaffeineEmailUnsubscribeResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid__UnsubscribeSuccess_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __UnsubscribeSuccess): _UnsubscribeSuccess {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : from_candid_BusinessProfile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionTier]): SubscriptionTier | null {
    return value.length === 0 ? null : from_candid_SubscriptionTier_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Guide]): Guide | null {
    return value.length === 0 ? null : from_candid_Guide_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsletterContent]): NewsletterContent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GuideId;
    title: string;
    topic: _Topic;
    content: string;
    isPublished: boolean;
    businessTypeTags: Array<string>;
    authorName: string;
    authorType: _AuthorType;
    publishedAt: [] | [_Timestamp];
    recommendedNext: Array<_GuideId>;
    excerpt: string;
    readTimeMinutes: bigint;
}): {
    id: GuideId;
    title: string;
    topic: Topic;
    content: string;
    isPublished: boolean;
    businessTypeTags: Array<string>;
    authorName: string;
    authorType: AuthorType;
    publishedAt?: Timestamp;
    recommendedNext: Array<GuideId>;
    excerpt: string;
    readTimeMinutes: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        topic: from_candid_Topic_n14(_uploadFile, _downloadFile, value.topic),
        content: value.content,
        isPublished: value.isPublished,
        businessTypeTags: value.businessTypeTags,
        authorName: value.authorName,
        authorType: from_candid_AuthorType_n16(_uploadFile, _downloadFile, value.authorType),
        publishedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.publishedAt)),
        recommendedNext: value.recommendedNext,
        excerpt: value.excerpt,
        readTimeMinutes: value.readTimeMinutes
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n21(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n25(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    provider: string;
    errorMessage: [] | [string];
    isHealthy: [] | [boolean];
    statusUrl: string;
    lastCheckedAt: [] | [string];
}): {
    provider: string;
    errorMessage?: string;
    isHealthy?: boolean;
    statusUrl: string;
    lastCheckedAt?: string;
} {
    return {
        provider: value.provider,
        errorMessage: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.errorMessage)),
        isHealthy: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.isHealthy)),
        statusUrl: value.statusUrl,
        lastCheckedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.lastCheckedAt))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalPublished: bigint;
    recentGuides: Array<_Guide>;
    pendingContributions: bigint;
}): {
    totalPublished: bigint;
    recentGuides: Array<Guide>;
    pendingContributions: bigint;
} {
    return {
        totalPublished: value.totalPublished,
        recentGuides: from_candid_vec_n33(_uploadFile, _downloadFile, value.recentGuides),
        pendingContributions: value.pendingContributions
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamSize: _TeamSize;
    signupDate: [] | [bigint];
    name: [] | [string];
    subscriptionTier: [] | [_SubscriptionTier];
    businessName: string;
    email: [] | [string];
    goals: Array<_Goal>;
    industryType: _IndustryType;
    location: string;
}): {
    teamSize: TeamSize;
    signupDate?: bigint;
    name?: string;
    subscriptionTier?: SubscriptionTier;
    businessName: string;
    email?: string;
    goals: Array<Goal>;
    industryType: IndustryType;
    location: string;
} {
    return {
        teamSize: from_candid_TeamSize_n37(_uploadFile, _downloadFile, value.teamSize),
        signupDate: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.signupDate)),
        name: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.name)),
        subscriptionTier: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.subscriptionTier)),
        businessName: value.businessName,
        email: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.email)),
        goals: from_candid_vec_n43(_uploadFile, _downloadFile, value.goals),
        industryType: from_candid_IndustryType_n46(_uploadFile, _downloadFile, value.industryType),
        location: value.location
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic_name: [] | [string];
}): {
    topic_name?: string;
} {
    return {
        topic_name: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.topic_name))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ContributionId;
    status: _ContributionStatus;
    title: string;
    topic: _Topic;
    content: string;
    authorName: string;
    rejectionReason: [] | [string];
    submittedAt: _Timestamp;
    reviewedAt: [] | [_Timestamp];
    businessContext: string;
    authorPrincipal: Principal;
}): {
    id: ContributionId;
    status: ContributionStatus;
    title: string;
    topic: Topic;
    content: string;
    authorName: string;
    rejectionReason?: string;
    submittedAt: Timestamp;
    reviewedAt?: Timestamp;
    businessContext: string;
    authorPrincipal: Principal;
} {
    return {
        id: value.id,
        status: from_candid_ContributionStatus_n54(_uploadFile, _downloadFile, value.status),
        title: value.title,
        topic: from_candid_Topic_n14(_uploadFile, _downloadFile, value.topic),
        content: value.content,
        authorName: value.authorName,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.rejectionReason)),
        submittedAt: value.submittedAt,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.reviewedAt)),
        businessContext: value.businessContext,
        authorPrincipal: value.authorPrincipal
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n60(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessPlanning: null;
} | {
    socialAds: null;
} | {
    branding: null;
} | {
    googleMaps: null;
} | {
    techUpgrades: null;
}): Topic {
    return "businessPlanning" in value ? Topic.businessPlanning : "socialAds" in value ? Topic.socialAds : "branding" in value ? Topic.branding : "googleMaps" in value ? Topic.googleMaps : "techUpgrades" in value ? Topic.techUpgrades : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    community: null;
}): AuthorType {
    return "admin" in value ? AuthorType.admin : "community" in value ? AuthorType.community : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: __UnsubscribeSuccess;
} | {
    Err: __UnsubscribeError;
}): {
    __kind__: "Ok";
    Ok: _UnsubscribeSuccess;
} | {
    __kind__: "Err";
    Err: _UnsubscribeError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid__UnsubscribeSuccess_n3(_uploadFile, _downloadFile, value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    solo: null;
} | {
    small: null;
} | {
    medium: null;
}): TeamSize {
    return "solo" in value ? TeamSize.solo : "small" in value ? TeamSize.small : "medium" in value ? TeamSize.medium : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    free: null;
} | {
    paid: null;
}): SubscriptionTier {
    return "free" in value ? SubscriptionTier.free : "paid" in value ? SubscriptionTier.paid : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessPlanning: null;
} | {
    socialAds: null;
} | {
    googleMaps: null;
}): Goal {
    return "businessPlanning" in value ? Goal.businessPlanning : "socialAds" in value ? Goal.socialAds : "googleMaps" in value ? Goal.googleMaps : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    retail: null;
} | {
    other: null;
} | {
    deli: null;
} | {
    consulting: null;
} | {
    salon: null;
} | {
    onlineServices: null;
} | {
    newBusiness: null;
} | {
    poolHall: null;
} | {
    restaurant: null;
}): IndustryType {
    return "retail" in value ? IndustryType.retail : "other" in value ? IndustryType.other : "deli" in value ? IndustryType.deli : "consulting" in value ? IndustryType.consulting : "salon" in value ? IndustryType.salon : "onlineServices" in value ? IndustryType.onlineServices : "newBusiness" in value ? IndustryType.newBusiness : "poolHall" in value ? IndustryType.poolHall : "restaurant" in value ? IndustryType.restaurant : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ContributionStatus {
    return "pending" in value ? ContributionStatus.pending : "approved" in value ? ContributionStatus.approved : "rejected" in value ? ContributionStatus.rejected : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProviderHealthStatus>): Array<ProviderHealthStatus> {
    return value.map((x)=>from_candid_ProviderHealthStatus_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Guide>): Array<Guide> {
    return value.map((x)=>from_candid_Guide_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contribution>): Array<Contribution> {
    return value.map((x)=>from_candid_Contribution_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n58(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function to_candid_BusinessProfile_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessProfile): _BusinessProfile {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_ContributionInput_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributionInput): _ContributionInput {
    return to_candid_record_n80(_uploadFile, _downloadFile, value);
}
function to_candid_Frequency_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): _Frequency {
    return to_candid_variant_n82(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_GuideFilter_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideFilter): _GuideFilter {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_GuideInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideInput): _GuideInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_IndustryType_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndustryType): _IndustryType {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_OutageFilter_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OutageFilter): _OutageFilter {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_TeamSize_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamSize): _TeamSize {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_Topic_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Topic): _Topic {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic?: Topic;
    keyword?: string;
    businessTypeTag?: string;
}): {
    topic: [] | [_Topic];
    keyword: [] | [string];
    businessTypeTag: [] | [string];
} {
    return {
        topic: value.topic ? candid_some(to_candid_Topic_n10(_uploadFile, _downloadFile, value.topic)) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none(),
        businessTypeTag: value.businessTypeTag ? candid_some(value.businessTypeTag) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    provider?: string;
    endDate?: string;
    incidentType?: string;
    startDate?: string;
}): {
    provider: [] | [string];
    endDate: [] | [string];
    incidentType: [] | [string];
    startDate: [] | [string];
} {
    return {
        provider: value.provider ? candid_some(value.provider) : candid_none(),
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        incidentType: value.incidentType ? candid_some(value.incidentType) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamSize: TeamSize;
    signupDate?: bigint;
    name?: string;
    subscriptionTier?: SubscriptionTier;
    businessName: string;
    email?: string;
    goals: Array<Goal>;
    industryType: IndustryType;
    location: string;
}): {
    teamSize: _TeamSize;
    signupDate: [] | [bigint];
    name: [] | [string];
    subscriptionTier: [] | [_SubscriptionTier];
    businessName: string;
    email: [] | [string];
    goals: Array<_Goal>;
    industryType: _IndustryType;
    location: string;
} {
    return {
        teamSize: to_candid_TeamSize_n68(_uploadFile, _downloadFile, value.teamSize),
        signupDate: value.signupDate ? candid_some(value.signupDate) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        subscriptionTier: value.subscriptionTier ? candid_some(to_candid_SubscriptionTier_n70(_uploadFile, _downloadFile, value.subscriptionTier)) : candid_none(),
        businessName: value.businessName,
        email: value.email ? candid_some(value.email) : candid_none(),
        goals: to_candid_vec_n72(_uploadFile, _downloadFile, value.goals),
        industryType: to_candid_IndustryType_n75(_uploadFile, _downloadFile, value.industryType),
        location: value.location
    };
}
function to_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    topic: Topic;
    content: string;
    authorName: string;
    businessContext: string;
}): {
    title: string;
    topic: _Topic;
    content: string;
    authorName: string;
    businessContext: string;
} {
    return {
        title: value.title,
        topic: to_candid_Topic_n10(_uploadFile, _downloadFile, value.topic),
        content: value.content,
        authorName: value.authorName,
        businessContext: value.businessContext
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    topic: Topic;
    content: string;
    businessTypeTags: Array<string>;
    authorName: string;
    recommendedNext: Array<GuideId>;
    excerpt: string;
    readTimeMinutes: bigint;
}): {
    title: string;
    topic: _Topic;
    content: string;
    businessTypeTags: Array<string>;
    authorName: string;
    recommendedNext: Array<_GuideId>;
    excerpt: string;
    readTimeMinutes: bigint;
} {
    return {
        title: value.title,
        topic: to_candid_Topic_n10(_uploadFile, _downloadFile, value.topic),
        content: value.content,
        businessTypeTags: value.businessTypeTags,
        authorName: value.authorName,
        recommendedNext: value.recommendedNext,
        excerpt: value.excerpt,
        readTimeMinutes: value.readTimeMinutes
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Topic): {
    businessPlanning: null;
} | {
    socialAds: null;
} | {
    branding: null;
} | {
    googleMaps: null;
} | {
    techUpgrades: null;
} {
    return value == Topic.businessPlanning ? {
        businessPlanning: null
    } : value == Topic.socialAds ? {
        socialAds: null
    } : value == Topic.branding ? {
        branding: null
    } : value == Topic.googleMaps ? {
        googleMaps: null
    } : value == Topic.techUpgrades ? {
        techUpgrades: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamSize): {
    solo: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == TeamSize.solo ? {
        solo: null
    } : value == TeamSize.small ? {
        small: null
    } : value == TeamSize.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    free: null;
} | {
    paid: null;
} {
    return value == SubscriptionTier.free ? {
        free: null
    } : value == SubscriptionTier.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    businessPlanning: null;
} | {
    socialAds: null;
} | {
    googleMaps: null;
} {
    return value == Goal.businessPlanning ? {
        businessPlanning: null
    } : value == Goal.socialAds ? {
        socialAds: null
    } : value == Goal.googleMaps ? {
        googleMaps: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndustryType): {
    retail: null;
} | {
    other: null;
} | {
    deli: null;
} | {
    consulting: null;
} | {
    salon: null;
} | {
    onlineServices: null;
} | {
    newBusiness: null;
} | {
    poolHall: null;
} | {
    restaurant: null;
} {
    return value == IndustryType.retail ? {
        retail: null
    } : value == IndustryType.other ? {
        other: null
    } : value == IndustryType.deli ? {
        deli: null
    } : value == IndustryType.consulting ? {
        consulting: null
    } : value == IndustryType.salon ? {
        salon: null
    } : value == IndustryType.onlineServices ? {
        onlineServices: null
    } : value == IndustryType.newBusiness ? {
        newBusiness: null
    } : value == IndustryType.poolHall ? {
        poolHall: null
    } : value == IndustryType.restaurant ? {
        restaurant: null
    } : value;
}
function to_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributionStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ContributionStatus.pending ? {
        pending: null
    } : value == ContributionStatus.approved ? {
        approved: null
    } : value == ContributionStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): {
    both: null;
} | {
    monthly: null;
} | {
    weekly: null;
} {
    return value == Frequency.both ? {
        both: null
    } : value == Frequency.monthly ? {
        monthly: null
    } : value == Frequency.weekly ? {
        weekly: null
    } : value;
}
function to_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Goal>): Array<_Goal> {
    return value.map((x)=>to_candid_Goal_n73(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
